### ISSUE TITLE
Cannot call method 'toString' of undefined

### ISSUE THREAD

**Issue by ryanmeador** [mostlyserious/riak-js#235]
I've been getting this error randomly from Riak-JS 1.0.3 when (I believe) attempting to get a key that has a conflict.  I'm unsure of exactly what is going on that leads up to this point because the stack trace isn't very illuminating.  I think there are two writes in very rapid succession that create the same key in a bucket that does not `allow_mult`, which I would expect to just lose one set of the data, but instead upon the next read of that key, the crash happens.  Again, that's my best guess, not a guarantee of what's actually happening.  Have you seen this before?

```
TypeError: Cannot call method 'toString' of undefined
 at [object Object]._parseMultipartMixed (/home/deploy/eventapp/backend/node_modules/riak-js/lib/http-meta.js:179:15)
 at HttpRequest.extractMultipartResponse (/home/deploy/eventapp/backend/node_modules/riak-js/lib/http-request.js:218:25)
 at HttpRequest.handleRequestEnd (/home/deploy/eventapp/backend/node_modules/riak-js/lib/http-request.js:275:19)
 at IncomingMessage.<anonymous> (/home/deploy/eventapp/backend/node_modules/riak-js/lib/http-request.js:160:21)
 at IncomingMessage.emit (events.js:117:20)
 at _stream_readable.js:944:16
 at process._tickDomainCallback (node.js:486:13)
```

**Comment by Quentin01** [comment]
I haven't seen this one since I use Riak-JS. I would look when I have time.
